-- ============================================================================
-- EAGLES CRM - CLIENTES ACADÉMICOS E INTEGRACIÓN CON EL CAMPUS
-- Ejecutar en el SQL Editor del proyecto Supabase DEL CRM.
-- No modifica ni elimina leads existentes.
-- ============================================================================

-- 1. CLIENTE ÚNICO DE LA ACADEMIA
-- Un cliente puede tener varios leads y comprar varios cursos.
create table if not exists public.academy_customers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  phone_normalized text,
  email text,
  email_normalized text,
  hotmart_customer_id text,
  created_from_lead_id bigint references public.leads(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists academy_customers_phone_unique
  on public.academy_customers (phone_normalized)
  where phone_normalized is not null and phone_normalized <> '';

create unique index if not exists academy_customers_email_unique
  on public.academy_customers (email_normalized)
  where email_normalized is not null and email_normalized <> '';

create unique index if not exists academy_customers_hotmart_unique
  on public.academy_customers (hotmart_customer_id)
  where hotmart_customer_id is not null and hotmart_customer_id <> '';

-- 2. RELACIONAR EL LEAD CON EL CLIENTE ACADÉMICO
alter table public.leads
  add column if not exists academy_customer_id bigint;

-- Estas columnas normalizan los datos que entrega el webhook de Hotmart.
-- Se agregan aquí porque no existen en la estructura actual del CRM.
alter table public.leads
  add column if not exists has_purchased boolean not null default false,
  add column if not exists hotmart_customer_id text,
  add column if not exists purchase_date timestamptz,
  add column if not exists purchase_amount numeric;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'leads_academy_customer_id_fkey'
      and conrelid = 'public.leads'::regclass
  ) then
    alter table public.leads
      add constraint leads_academy_customer_id_fkey
      foreign key (academy_customer_id)
      references public.academy_customers(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists leads_academy_customer_idx
  on public.leads (academy_customer_id);

-- 3. ACCESO QUE ESE CLIENTE TIENE EN EL OTRO SUPABASE (CAMPUS)
create table if not exists public.customer_campus_access (
  id bigint generated by default as identity primary key,
  academy_customer_id bigint not null
    references public.academy_customers(id) on delete cascade,
  source_lead_id bigint references public.leads(id) on delete set null,
  course_id text not null,
  campus_user_id uuid,
  campus_username text not null,
  status text not null default 'active'
    check (status in ('active', 'failed', 'revoked')),
  created_by uuid references auth.users(id) on delete set null,
  provisioned_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (academy_customer_id, course_id)
);

create index if not exists customer_campus_access_customer_idx
  on public.customer_campus_access (academy_customer_id);

create index if not exists customer_campus_access_lead_idx
  on public.customer_campus_access (source_lead_id);

-- 4. updated_at AUTOMÁTICO
create or replace function public.set_academy_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_academy_customers_updated_at on public.academy_customers;
create trigger set_academy_customers_updated_at
before update on public.academy_customers
for each row execute function public.set_academy_updated_at();

drop trigger if exists set_customer_campus_access_updated_at on public.customer_campus_access;
create trigger set_customer_campus_access_updated_at
before update on public.customer_campus_access
for each row execute function public.set_academy_updated_at();

-- 5. SEGURIDAD
-- El navegador no consulta estas tablas directamente. Únicamente las rutas
-- privadas del CRM, después de comprobar que la sesión pertenece a un admin.
alter table public.academy_customers enable row level security;
alter table public.customer_campus_access enable row level security;

revoke all on public.academy_customers from anon, authenticated;
revoke all on public.customer_campus_access from anon, authenticated;

grant all privileges on public.academy_customers to service_role;
grant all privileges on public.customer_campus_access to service_role;
grant usage, select on sequence public.academy_customers_id_seq to service_role;
grant usage, select on sequence public.customer_campus_access_id_seq to service_role;

-- ============================================================================
-- RESULTADO:
-- leads.academy_customer_id -> academy_customers.id
-- academy_customers.id      -> customer_campus_access.academy_customer_id
-- El mismo número se guarda en el Campus como crm_customer_id.
-- ============================================================================
